using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;

namespace Cactoos.Reflection
{
    /// <summary>
    /// Gets types, which are not generated by the compiler or useless.
    /// </summary>
    public class NotGeneratedTypes : IEnumerable<Type>
    {
        private IEnumerable<Type> _source;

        public NotGeneratedTypes(IScalar<System.Reflection.Assembly> assembly) : this(new AssemblyTypes(assembly))
        {

        }

        public NotGeneratedTypes(System.Reflection.Assembly assembly) : this(new AssemblyTypes(assembly))
        {

        }

        public NotGeneratedTypes(IEnumerable<Type> source)
        {
            _source = source;
        }

        public IEnumerator<Type> GetEnumerator()
        {
            // Ignore useless types
            return _source.Where(type =>
                       !(type.Name.Contains("<PrivateImplementationDetails>") ||
                       type.Name.Contains("+") ||
                       type.Name.Contains(">") ||
                       type.Name.Contains("<") || // C# compiler generated classes
                       type.Name.Contains("+_Closure") || // VB.NET compiler generated classes
                       type.Name.Contains(".__") || // System.Runtime.CompilerServices.*
                       type.Name.Contains("Interop+") || // System.IO.FileSystem, System.Net.Sockets, etc
                       type.Name.Contains("c__DisplayClass") ||
                       type.Name.Contains("d__") ||
                       type.Name.Contains("f__AnonymousType") ||
                       type.Name.Contains("o__") ||
                       type.Name.Contains("__DynamicallyInvokableAttribute") ||
                       type.Name.Contains("ProcessedByFody") ||
                       type.Name.Contains("FXAssembly") ||
                       type.Name.Contains("ThisAssembly") ||
                       type.Name.Contains("AssemblyRef") ||
                       type.Name.Contains("MS.Internal") ||
                       type.Name.Contains("::") ||
                       type.Name.Contains("\\*") ||
                       type.Name.Contains("_extraBytes_") ||
                       type.Name.Contains("CppImplementationDetails"))
                   ).GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return GetEnumerator();
        }
    }
}
